package greenDao;

import greenDao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CONVERSATION_GROUP.
 */
public class ConversationGroup {

    private Long id;
    private long ConversationId;
    private long ContactId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ConversationGroupDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ConversationGroup() {
    }

    public ConversationGroup(Long id) {
        this.id = id;
    }

    public ConversationGroup(Long id, long ConversationId, long ContactId) {
        this.id = id;
        this.ConversationId = ConversationId;
        this.ContactId = ContactId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getConversationGroupDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getConversationId() {
        return ConversationId;
    }

    public void setConversationId(long ConversationId) {
        this.ConversationId = ConversationId;
    }

    public long getContactId() {
        return ContactId;
    }

    public void setContactId(long ContactId) {
        this.ContactId = ContactId;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
