package greenDao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greenDao.Contact;
import greenDao.Conversation;
import greenDao.Message;
import greenDao.ConversationGroup;

import greenDao.ContactDao;
import greenDao.ConversationDao;
import greenDao.MessageDao;
import greenDao.ConversationGroupDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactDaoConfig;
    private final DaoConfig conversationDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig conversationGroupDaoConfig;

    private final ContactDao contactDao;
    private final ConversationDao conversationDao;
    private final MessageDao messageDao;
    private final ConversationGroupDao conversationGroupDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        conversationDaoConfig = daoConfigMap.get(ConversationDao.class).clone();
        conversationDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        conversationGroupDaoConfig = daoConfigMap.get(ConversationGroupDao.class).clone();
        conversationGroupDaoConfig.initIdentityScope(type);

        contactDao = new ContactDao(contactDaoConfig, this);
        conversationDao = new ConversationDao(conversationDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        conversationGroupDao = new ConversationGroupDao(conversationGroupDaoConfig, this);

        registerDao(Contact.class, contactDao);
        registerDao(Conversation.class, conversationDao);
        registerDao(Message.class, messageDao);
        registerDao(ConversationGroup.class, conversationGroupDao);
    }
    
    public void clear() {
        contactDaoConfig.getIdentityScope().clear();
        conversationDaoConfig.getIdentityScope().clear();
        messageDaoConfig.getIdentityScope().clear();
        conversationGroupDaoConfig.getIdentityScope().clear();
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public ConversationDao getConversationDao() {
        return conversationDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public ConversationGroupDao getConversationGroupDao() {
        return conversationGroupDao;
    }

}
